version: 2.1

jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - run:
          name: 'Hello'
          command: 'echo Hello'

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
